let values = [
   'Maria becerra - Ojala.mp3',
   'Maluma - Sobrio.mp3',
   'Maluma - Hawai.mp4',
   'Ventino - No.mp4',
   'Ventino - Casi Igual.mp4',
   'Rombai - Bailando.mp3',
   'Maria Becerra - Episodios.mp3',
   'Dua Lipa, DaBaby - Levitating (feat. DaBaby).mp3',
   'Olivia Rodrigo - Good 4 u.mp3',
   'Bad Bunny, Jhay Cortez - DÁKITI.mp4',
   'Rauw Alejandro - Todo De Ti.webm',
   'Tini y María Becerra - Miénteme.mp4',
   'María Becerra, J Balvin - Qué Más Pues?.mp3',
   'Los Legendarios, Wisin, Jhay Cortez - Fiel.mp4',
   'Karol G, Anuel AA, J Balvin - LOCATION.mp3',
   'Ptazeta, Farina, Juacko - Trakatá.mp4',
   'Natti Natasha, Becky G - Ram Pam Pam.mp3',
   'Omar Montes, Ana Mena, Maffio - Solo.webm',
   'Nathy Peluso Bizarrap - Music Sessions #36.mp3',
   'Lola Indigo, Danna Paola, Denise Rosenthal - Santería.mp3',
   'Lola Indigo, TINI, Belinda - La Niña de la Escuela.mp4',
   'Karol G y Nicki Minaj - Tusa.mp3',
   'Ana Mena y Rocco Hunt - A Un Paso De La Luna.webm',
   'Rosalía y Ozuna - Yo x Ti, Tu x Mi.mp4',
   'Sech, Daddy Yankee, J Balvin, ROSALÍA, Farruko - Relación Remix.mp3',
   'Anuel AA - El Manual.mp3',
   'Lola Índigo, Lalo Ebratt, Rauw Alejandro - 4 besos.webm',
   'ROSALÍA, J Balvin, El Guincho - Con Altura.mp3',
   'J Balvin - Morado.webm',
   'Anuel AA, Daddy Yankee, KAROL G, J Balvin, Ozuna - China.mp3',
   'Danny Ocean - Me Rehúso.mp4',
   'Bad Gyal y Omar Montes - Alocao.mp3',
   'Comando Tiburon, Mach and Daddy - Pasado pisado.m4a',
   'DJ Snake, J Balvin, Tyga - Loco Contigo.m4a',
   'Natti Natasha y Becky G - Sin Pijama.webm',
   'Reik, J Balvin, Lalo Ebratt - Indeciso.mp4',
   'Don Omar - Pobre Diabla.mp3',
   'Aitana y Lola Índigo - Me Quedo.webm',
   'Daddy Yankee - Lo Que Pasó, Pasó.mp4',
   'Don Omar - Dile.mp4',
   'Nicki Jam y Anuel AA - Whine Up.mp4',
   'Daddy Yankee - Limbo.mp3',
   'CNCO - Reggaetón Lento (Bailemos).mp4',
   'Aventura y Judy Santos - Obsesión.webm',
   'Daddy Yankee y Snow - Con Calma.mp4',
   'Sebastián Yatra - Traicionera.mp3',
   'Juan Magán - Bailando por Ahí.mp4',
   'Daddy Yankee y Nicky Jam - Donde Están Las Gatas.mp4',
   'Zion & Lennox, J Balvin - Otra vez.mp4',
   'Gente de Zona y Marc Anthony - La Gozadera.mp3',
   'Thalia, Natti Natasha - No Me Acuerdo.m4a',
   'Shakira y Carlos Vives - La Bicicleta.webm',
   'Pedro Capó, Farruko - Calma Remix.mp4',
   'Calle 13 - Atrévete-Te-Te.mp4',
   'Reik, Ozuna, Wisin - Me Niego.mp3',
   'Natti Natasha, Cazzu, Farina, La Duraca - Las Nenas.webm',
   'Bad Bunny - Yo Perreo Sola.webm',
   'Anuel AA - Reggaetonera.webm',
   'Bad Bunny, Nicki Jam - BAD CON NICKY.mp4',
   'Bad Gyal, Juanka - Blin Blin.webm',
   'Alberto Gambino - Purpurina.mp3',
   'Eddy Lover - Rueda rueda.mp4',
   'Lola Indigo, Don Patricio - Lola Bunny.mp3',
   'C. Tangana - Mala Mujer.m4a',
   'K-Narias - No Te Vistas Que No Vas.mp3',
   'Fuego - Una Vaina Loca.mp4',
   'Big Yamo, Vato 18k - Entre la Playa Ella y Yo.mp3',
   'Daddy Yankee - ¿Qué Tengo Que Hacer?.webm',
   'Plan B - Candy.mp4',
   'Daddy Yankee - Gasolina.m4a',
   'Don Omar, Natti Natasha - Dutty Love.mp4',
   'J Balvin - Reggaeton.webm',
   'Lunay, Daddy Yankee, Bad Bunny - Soltera Remix.mp3',
   'Bad Bunny, Tainy - Callaita.m4a',
   'Aitana, Ana Guerra - Lo Malo.m4a',
   'Romeo Santos, Daddy Yankee, Nicky Jam - Bella y Sensual.webm',
   'J Balvin, Willy William - Mi Gente.mp4',
   'Nicki Jam - El Amante.mp4',
   'Tito "El Bambino", Zion, Lennox - Mi Cama Huele a Ti.mp4',
   'Farruko, Bad Bunny, Rvssian - Krippy Kush.mp3',
   'Luis Fonsi, Daddy Yankee - Despacito.webm'
]

//cadenas
let cadenas = ['Buenos Aires','unica','juancarlos@gmail.es','conocedor','Copa rota','convencido','$134.43','camiones','JC21','alfredo@hotmail.com','comicionado','google','PO98','renata@gmail.com','$9823.21','Río Mamore','$176.67','Av. Palacios','Calle Rocabado','Puerto Acosta','BY67','Av. San Marcos','$8762.00','#@!><&<//>','=?)(&','RR77','$3300.99','Puente Carlona del Norte','Nueva York','Av. Nueva Generación','joelgarcia@gmail.com','IU12','*&$>?#!{-?<','Edif. Ferrondo','Calle 19','romanfer@usomin.gob.bo','OO90','FTM s.r.l.','$1900867','0x8975fba342a421abf45c127','Reus','Condominio #9879','Asturia','ercer@hotmail.com','cmendez@outlook.com','Leaños Robles','José Alberto', '$()>$<)&9%>-.¡¿','faock.reaul@outlook.com','Puente Sevilla','$786.90','GT55','PR98','PI31','OPPO','Leaños'];